### PR TITLE
add org.feichtmeier.Musicpod

### PR DESCRIPTION
**Pull request by Feichtmeier**
### Please confirm your submission meets all the criteria

Please describe your application briefly below.

- [ ] I have read the [App Requirements][reqs] and [App Maintenance][maint] pages.
- [ ] My pull request follows the instructions at [App Submission][submission].
- [x] I have [built][build] and tested the submission locally.
- [ ] I am using only the minimal set of permissions. *(If not, please explain each non-standard permission.)*
- [ ] All assets referenced in the manifest are redistributable by any party.  If not, the unredistributable parts are using an extra-data source type.
- [x] I am an author/developer/upstream contributor of the project. If not, I contacted upstream developers about submitting their software to Flathub. **Link:**
- [ ] The domain used for the application ID is controlled by the application developers either directly or through the code hosting (e.g. GitHub, GitLab, SourceForge, etc.). The [application id guidelines][app-id] are followed.
- [ ] Any additional patches or files have been submitted to the upstream projects concerned. *(If not, explain why.)*

[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[maint]: https://docs.flathub.org/docs/for-app-authors/maintanance
[submission]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission
[app-id]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@12people @popey 

I followed the instructions by @12people in https://github.com/ubuntu-flutter-community/musicpod/blob/main/flatpak/README
Only needed to change the downloads tag I think
for this release (uploaded the generated tar https://github.com/ubuntu-flutter-community/musicpod/releases/tag/1.2.0)

Could one of you check if this is correct before I close this PR here and open the pull request on flathub?

**Comment by cat-master21** [comment]
@Feichtmeier I know I suggested it earlier, but you could use my version of the Flatpak manifest at https://github.com/cat-master21/flathub/blob/org.feichtmeier.Musicpod/org.feichtmeier.Musicpod.json instead with the main difference being that it has arm64 support + it does not rely on the Flatpak infrastructure code.

The main difference is that my version downloads the Snap and creates a Flatpak from it instead making another build.

**Comment by Feichtmeier** [comment]
> @Feichtmeier I know I suggested it earlier, but you could use my version of the Flatpak manifest at https://github.com/cat-master21/flathub/blob/org.feichtmeier.Musicpod/org.feichtmeier.Musicpod.json instead with the main difference being that it has arm64 support + it does not rely on the Flatpak infrastructure code.
> 
> The main difference is that my version downloads the Snap and creates a Flatpak from it instead making another build.

Hi :wave: Thanks for diving into my shitshow :laughing: 

I have abs. no idea what I am doing there, just followed @12people instructions.
What would I need to change?
I used the json file (I think this is the manifest) that was created by 12people dart generator
I think it is linked to a release, I chose the latest now 1.2.0

Is your manifest also linked to a release? Where does the binary/tar come from then?

Edit: as the tar was built on this (very slow) amd64 arch, it will not run on arm64 for sure
(on snapcraft arm64 is created automatically in an arm64 container)

**Comment by popey** [comment]
I also noticed the lack of arm64 support. 
I'm not a fan of repacking one package as another, especially with the modern formats which can cater just fine for building from source. It's storing up a problem for later, IMO.

**Comment by AtiusAmy** [comment]
> I also noticed the lack of arm64 support. I'm not a fan of repacking one package as another, especially with the modern formats which can cater just fine for building from source. It's storing up a problem for later, IMO.

afaik I haven't seen a Flutter app built from source in Flathub, they're mostly just unpackaged tar built from another way

**Comment by AtiusAmy** [comment]
> Edit: as the tar was built on this (very slow) amd64 arch, it will not run on arm64 for sure

The binary on cat-master's script is taken directly from the snap store

**Comment by cat-master21** [comment]
Indeed it is @AtiusAmy, this is what the Spotify Flatpack also does to and it works: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json, so it is your choice @Feichtmeier.

**Comment by Feichtmeier** [comment]
> Indeed it is @AtiusAmy, this is what the Spotify Flatpack also does to and it works: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json, so it is your choice @Feichtmeier.

Okay, so all I need to do is use your manifest file?

**Comment by AtiusAmy** [comment]
> > Indeed it is @AtiusAmy, this is what the Spotify Flatpack also does to and it works: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json, so it is your choice @Feichtmeier.
> 
> Okay, so all I need to do is use your manifest file?

Should work yeah

**Comment by Feichtmeier** [comment]
alright I use the version from @cat-master21 now

do you think I could create this pull request now on flathub?

**Comment by popey** [comment]
If you've been through the checklist, and you're conformant with the flathub packaging standards, yes, I'd get the ball rolling over there.

**Comment by Feichtmeier** [comment]
okay done, lets see what happens next lol

**Pull request closed without merging**
